title: House Calls Plus Inc.
themeColor: "#6d64e8"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  style: compressed
